import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import SessionProvider from './components/SessionProvider';
import Sidebar from './components/Sidebar';
import TopNavbar from './components/TopNavbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  // Redirect logic here if session is null

  return (
    <html lang="en">
      <body className={`${inter.className} flex relative`}>
        <SessionProvider session={session}>
          {/* Sidebar */}
          <div className="flex-none">
            <Sidebar />
          </div>
          
          {/* Main content area with Top Navbar */}
          <div className="flex-1 flex flex-col min-h-screen">
            <TopNavbar />
            <main className="flex-1 overflow-auto">
              {children}
            </main>
          </div>

          {/* Animated GIF in the bottom right corner */}
          <div className="absolute bottom-0 right-0 mb-4 mr-4">
            <img 
              src="https://cdn.7tv.app/emote/62f56f44971f4d663eb618ba/4x.gif" 
              alt="Animated Emote" 
              style={{ width: '150px', height: '150px' }}
            />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
